exclude: docs
repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.0.1
    hooks:
      - id: reorder-python-imports
        language_version: python3
        args: [--py3-plus]
        exclude: &exc "(^dynaconf/vendor+.|^venv/+.|^.venv/+.|^env/+.|^.tox/+.|^build/+.)"
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        args: [--line-length=79]
        language_version: python3
        exclude: *exc
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        language_version: python3
        exclude: *exc
      - id: end-of-file-fixer
        language_version: python3
        exclude: *exc
      - id: check-yaml
        language_version: python3
        exclude: *exc
      - id: check-merge-conflict
        language_version: python3
        exclude: *exc
      - id: debug-statements
        language_version: python3
        exclude: *exc
      - id: fix-encoding-pragma
        language_version: python3
        exclude: *exc
        args: [--remove]
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ['--ignore=F403,W504,W503,F841,E401,F401,E402']
        language_version: python3
        exclude: *exc
